### ISSUE TITLE
Too many incidental dependencies.

### ISSUE THREAD

**Issue by shurcooL** [sourcegraph/syntaxhighlight#15]
This issue is largely documented downstream at https://github.com/shurcooL/go/issues/19#issuecomment-97699653, but to quickly summarize:

After #11 was merged, `syntaxhighlight` package now indirectly imports an extremely large number of imports that are largely unrelated and unneeded to the core functionality of this package.

[![image](https://cloud.githubusercontent.com/assets/1924134/7408704/6cd28078-eed4-11e4-96ef-ea035e71ce6c.png)](https://godoc.org/github.com/sourcegraph/syntaxhighlight?import-graph&hide=1)

https://godoc.org/github.com/sourcegraph/syntaxhighlight?import-graph&hide=1

The vast majority of that is coming from the two imports `sourcegraph.com/sourcegraph/go-sourcegraph/sourcegraph` and `sourcegraph.com/sourcegraph/vcsstore/vcsclient` which are only needed to pull in the following types:

- [`vcsstore.FileWithRange`](https://sourcegraph.com/sourcegraph.com/sourcegraph/vcsstore@b71244de730e9d584392cf64c7b3b8c87e0b9044/.GoPackage/sourcegraph.com/sourcegraph/vcsstore/vcsclient/.def/FileWithRange)
- [`sourcegraph.SourceCode`](https://sourcegraph.com/sourcegraph.com/sourcegraph/go-sourcegraph@e50888d3248bf6f142f19fcc1299247c72e70866/.GoPackage/sourcegraph.com/sourcegraph/go-sourcegraph/sourcegraph/.def/SourceCode)
- [`sourcegraph.SourceCodeLine`](https://sourcegraph.com/sourcegraph.com/sourcegraph/go-sourcegraph@e50888d3248bf6f142f19fcc1299247c72e70866/.GoPackage/sourcegraph.com/sourcegraph/go-sourcegraph/sourcegraph/.def/SourceCodeLine)
- [`sourcegraph.SourceCodeToken`](https://sourcegraph.com/sourcegraph.com/sourcegraph/go-sourcegraph@e50888d3248bf6f142f19fcc1299247c72e70866/.GoPackage/sourcegraph.com/sourcegraph/go-sourcegraph/sourcegraph/.def/SourceCodeToken)

Despite those types being small, the packages that contain them are higher level and import many other dependencies.

We should fix this so that users of `syntaxhighlight` that only need the core functionality and do not use the `NilAnnotator` should not need to pull in that many dependencies.

**Comment by shurcooL** [comment]
I'm planning to tackle this now.

I've been thinking about how to best resolve this, but so far the best idea I've come up with is this.

We can simply move `NilAnnotator` and the needed imports into a separate package that imports `syntaxhighlight`. It could be a subpackage `"github.com/sourcegraph/syntaxhighlight/tokenizer"` or a separate repository.

That could be a temporary solution until we have something better. But it would resolve the issue and not cause many problems. Thoughts? /cc @gbbr @sqs

**Comment by gbbr** [comment]
I am removing this functionality and putting it into the app for now as it is mostly irrelevant to the purpose of this package. Will close this issue as soon as that has been completed.

**Comment by shurcooL** [comment]
The import graph looks a lot better now!

[![image](https://cloud.githubusercontent.com/assets/1924134/7579748/88d3b772-f81d-11e4-87a3-80bacd683486.png)](http://godoc.org/sourcegraph.com/sourcegraph/syntaxhighlight?import-graph&hide=1)

http://godoc.org/sourcegraph.com/sourcegraph/syntaxhighlight?import-graph&hide=1

**Comment by gbbr** [comment]
LOL!
